sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '4'
  - stable
before_install:
  - npm i -g npm
after_success: 'travis-after-all && npm run pages && npm run semantic-release'
